### ISSUE TITLE
Demo on codepen uses rawgit instead of cdn.rawgit

### ISSUE THREAD

**Issue by Maximilianos** [jimoong/mosaigrid#1]
Hey,

Cool grid and cool demo :)

Just letting you know you should use http://cdn.rawgit.com instead of http://rawgit.com in your codepen
because right now the demo is broken since you are over quota!

http://cdn.rawgit doesn't have a request limit.

**Comment by jimoong** [comment]
Oh, thanks, Max. really good to know. will fix it soon. :)

**Comment by jimoong** [comment]
It's fixed now.
